apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: default
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 5000        # Service port
      targetPort: 5000  # Container port
  type: ClusterIP      # Internal only (use NodePort/LoadBalancer if exposing outside)
