name: CI-CD-Production
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  # ---------------- Backend Security Scan ----------------
  backend-security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend
        uses: actions/checkout@v3

      - name: Install Snyk
        run: npm install -g snyk

      - name: Backend Dependency Scan
        run: snyk test --all-projects --severity-threshold=high

  # ---------------- Frontend Security Scan ----------------
  frontend-security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3

      - name: Install Snyk
        run: npm install -g snyk

      - name: Frontend Dependency Scan
        run: snyk test --all-projects --severity-threshold=high

  # ---------------- Backend Docker Build & Scan ----------------
  backend-build-and-push:
    runs-on: ubuntu-latest
    needs: backend-security-checks
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/3-tier-app-backend:latest

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/3-tier-app-backend:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: false

  # ---------------- Frontend Docker Build & Scan ----------------
  frontend-build-and-push:
    runs-on: ubuntu-latest
    needs: frontend-security-checks
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/3-tier-app-frontend:latest

      - name: Scan Docker Image with Trivy
        uses: aquasecurity/trivy-action@v1
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/3-tier-app-frontend:latest
          severity: CRITICAL,HIGH
          ignore-unfixed: false

  # ---------------- Kubernetes Deployment ----------------
  k8s-yaml-deploy:
    runs-on: self-hosted
    needs:
      - backend-build-and-push
      - frontend-build-and-push
    steps:
      - uses: actions/checkout@v3

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/staging/

      - name: Restart deployments/statefulsets
        run: kubectl rollout restart deployment,statefulset
