name: CI-CD
permissions:
  contents: read
on:
  push:
    branches:
      - main

jobs:
  # ---------------- Backend Security Checks ----------------
  backend-security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend
        uses: actions/checkout@v3

      - name: Backend Dependency Scan
        run: |
          npm install -g snyk        # install Snyk CLI
          snyk test || true          # run scan but don't fail workflow

  # ---------------- Frontend Security Checks ----------------
  frontend-security-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3

      - name: Frontend Dependency Scan
        run: |
          npm install -g snyk
          snyk test || true

  # ---------------- Backend Build & Push ----------------
  backend-build-and-push:
    runs-on: ubuntu-latest
    needs: backend-security-checks
    steps:
      - name: Checkout backend
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/3-tier-app-backend:latest

  # ---------------- Frontend Build & Push ----------------
  frontend-build-and-push:
    runs-on: ubuntu-latest
    needs: frontend-security-checks
    steps:
      - name: Checkout frontend
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/3-tier-app-frontend:latest

  # ---------------- Kubernetes Deployment ----------------
  k8s-yaml-deploy:
    runs-on: self-hosted
    needs:
      - backend-build-and-push
      - frontend-build-and-push
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/

      - name: Restart Kubernetes deployments/statefulsets
        run: kubectl rollout restart deployment,statefulset
